name: a2c

actor: 
  network: mlp
  network_params:
    layer: 3
    neuron_per_layer: 64

  solver: RMSprop
  solver_params:
    learning_rate: 5.0e-5
    rho: 0.99
    epsilon: 1.0e-5

  # solver: Adam
  # solver_params:
  #   learning_rate: 1e-4
  #   beta_1: 0.5
  #   epsilon: 1.0e-10

  max_grad_norm: 0.5
  ent_coef: 0.01

critic: 
  network: mlp
  network_params:
    layer: 3
    neuron_per_layer: 64

  solver: RMSprop
  solver_params:
    learning_rate: 5.0e-5
    rho: 0.99
    epsilon: 1.0e-5

  # solver: Adam
  # solver_params:
  #   learning_rate: 1e-4
  #   beta_1: 0.5
  #   epsilon: 1.0e-10

  max_grad_norm: 0.5

train:
  epoch: 1000
  step: 32
  batch: 128
  log_epoch: 1
  evaluate_epoch: 1
  save_epoch: 5

test:
  step: 500

value:
  gamma: 0.9
  # nstep: 10


