name: test_environment

# Instance spec, could be multiple instance in the future
instance: &instance
  # price per instance per hour
  price: 1
  capacity: 1000
  max_instances: 100
  min_instances: 1

  # for simplicity, for now the start and shutdown process can be finished within one time step, so in each time step, the instance is either on or off
  # start_time: 1 # e.g start all the daemons 
  # shutdown_time: 1 # return uncompleted request to queue (this process will not be considered for now), finish log then shut down

random_pattern: &random_pattern
  name: random_pattern

sin_pattern: &sin_pattern
  name: sin_pattern
  # (sin((x * 2pi)/a + b * pi) + d) * c + noise
  a: 360 # minute, one recycle every 6 hours
  b: -0.5
  c: 20000
  d: 1.5
  # gaussion noise std
  std: 10000

# Request spec
# for simplicity, for now each request has 1 unit load per 1 time step
request:
  influx_pattern: *sin_pattern # sine, or even from file
  max_requests: 100000
  min_requests: 0
  max_queue_size: 1000000

environment:
  step_time: 1 # min
  # queue_size: unlimited for simplicity
  max_length: 500 # max length of episode